---
version: "2.1"
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - MONGO_USER=unifi
      - MONGO_PASS=DevDeividMoura
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
   #   - MONGO_TLS= #optional
   #   - MONGO_AUTHSOURCE= #optional
    volumes:
      - unifi-vol:/config
    ports:
      - 8888:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      # - 8880:8880
    networks:
      unifi:
    restart: unless-stopped

  unifi-db:
    image: docker.io/mongo:4.4
    container_name: unifi-db
    volumes:
      - unifi-db-vol:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      unifi:
    restart: unless-stopped

networks:
  unifi:

volumes:
  unifi-vol:
    name: unifi-vol
  unifi-db-vol:
    name: unifi-db-vol
